name: Test examples

on:
  push:
    paths:
      - .github/workflows/test_examples.yml
      - modules/**
      - devenv.nix
      - devenv.yaml

env:
  DEVENV_VERSION: v0.6.3

jobs:
  test_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install --accept-flake-config tarball+https://install.devenv.sh/${DEVENV_VERSION}
        shell: sh
      - name: Test SW6 example
        run: |
          echo running on branch ${GITHUB_REF_NAME}
          cd examples/sw6
          sed -i "s,kellerkinderDE/devenv-shopware?ref=v1.0.0,kellerkinderDE/devenv-shopware?ref=${GITHUB_REF_NAME}," devenv.yaml
          devenv ci -vvv
          devenv shell echo ok
      - name: Test SW5 example
        run: |
          echo running on branch ${GITHUB_REF_NAME}
          cd examples/sw5
          sed -i "s,kellerkinderDE/devenv-shopware?ref=v1.0.0,kellerkinderDE/devenv-shopware?ref=${GITHUB_REF_NAME}," devenv.yaml
          devenv ci -vvv
          devenv shell echo ok
